// LaTeX Template Registry
// Defines preamble/package configurations for each journal template.
// Does NOT include full document content — only the \documentclass, \usepackage, and preamble settings.

export interface LaTeXTemplate {
  id: string;
  name: string;
  documentClass: string;
  documentOptions: string[];
  packages: LaTeXPackage[];
  preambleExtras?: string[];
  bibliographyStyle: string;
  bibliographyEngine: 'bibtex' | 'biber';
  notes?: string;
}

export interface LaTeXPackage {
  name: string;
  options?: string[];
}

export const latexTemplateRegistry: LaTeXTemplate[] = [
  {
    id: 'ieee',
    name: 'IEEE Transactions',
    documentClass: 'IEEEtran',
    documentOptions: ['journal', 'twocolumn', '10pt'],
    packages: [
      { name: 'cite' },
      { name: 'amsmath', options: ['cmex10'] },
      { name: 'amssymb' },
      { name: 'graphicx' },
      { name: 'hyperref', options: ['colorlinks=false'] },
      { name: 'algorithm2e' },
      { name: 'booktabs' },
      { name: 'siunitx' },
      { name: 'balance' },
    ],
    preambleExtras: [
      '\\interdisplaylinepenalty=2500',
    ],
    bibliographyStyle: 'IEEEtran',
    bibliographyEngine: 'bibtex',
    notes: 'Use IEEEtran.cls from IEEE. Two-column, numbered citations.',
  },
  {
    id: 'ieee-conference',
    name: 'IEEE Conference',
    documentClass: 'IEEEtran',
    documentOptions: ['conference', 'twocolumn', '10pt'],
    packages: [
      { name: 'cite' },
      { name: 'amsmath' },
      { name: 'amssymb' },
      { name: 'graphicx' },
      { name: 'hyperref', options: ['colorlinks=false'] },
      { name: 'booktabs' },
    ],
    bibliographyStyle: 'IEEEtran',
    bibliographyEngine: 'bibtex',
    notes: 'IEEE conference proceedings (two-column). Max 6 pages.',
  },
  {
    id: 'acm',
    name: 'ACM Computing',
    documentClass: 'acmart',
    documentOptions: ['sigconf', 'nonacm'],
    packages: [
      { name: 'amsmath' },
      { name: 'graphicx' },
      { name: 'booktabs' },
      { name: 'microtype' },
      { name: 'hyperref' },
    ],
    bibliographyStyle: 'ACM-Reference-Format',
    bibliographyEngine: 'biber',
    notes: 'ACM SIG proceedings. Requires acmart.cls.',
  },
  {
    id: 'acm-conference',
    name: 'ACM Conference (CHI/SIGCHI)',
    documentClass: 'acmart',
    documentOptions: ['sigchi'],
    packages: [
      { name: 'amsmath' },
      { name: 'graphicx' },
      { name: 'booktabs' },
      { name: 'hyperref' },
    ],
    bibliographyStyle: 'ACM-Reference-Format',
    bibliographyEngine: 'biber',
    notes: 'CHI / SIGCHI conference format.',
  },
  {
    id: 'elsevier',
    name: 'Elsevier Journal',
    documentClass: 'elsarticle',
    documentOptions: ['review', '12pt', 'authoryear'],
    packages: [
      { name: 'amsmath' },
      { name: 'amssymb' },
      { name: 'graphicx' },
      { name: 'booktabs' },
      { name: 'lineno' },
      { name: 'hyperref' },
      { name: 'natbib' },
    ],
    preambleExtras: [
      '\\journal{Journal Name}',
    ],
    bibliographyStyle: 'elsarticle-harv',
    bibliographyEngine: 'bibtex',
    notes: 'Requires elsarticle.cls. Use numbered variant with elsarticle-num.',
  },
  {
    id: 'elsevier-procedia',
    name: 'Elsevier Procedia (Conference)',
    documentClass: 'elsarticle',
    documentOptions: ['5p', 'twocolumn'],
    packages: [
      { name: 'amsmath' },
      { name: 'graphicx' },
      { name: 'booktabs' },
      { name: 'hyperref' },
    ],
    bibliographyStyle: 'elsarticle-num',
    bibliographyEngine: 'bibtex',
  },
  {
    id: 'springer',
    name: 'Springer Nature',
    documentClass: 'sn-article',
    documentOptions: [],
    packages: [
      { name: 'amsmath' },
      { name: 'amssymb' },
      { name: 'graphicx' },
      { name: 'booktabs' },
      { name: 'hyperref' },
      { name: 'natbib' },
    ],
    bibliographyStyle: 'sn-aps',
    bibliographyEngine: 'bibtex',
    notes: 'Requires sn-article.cls from Springer Nature.',
  },
  {
    id: 'lncs',
    name: 'Springer Conference (LNCS)',
    documentClass: 'llncs',
    documentOptions: [],
    packages: [
      { name: 'amsmath' },
      { name: 'graphicx' },
      { name: 'booktabs' },
      { name: 'hyperref', options: ['pdftex'] },
    ],
    bibliographyStyle: 'splncs04',
    bibliographyEngine: 'bibtex',
    notes: 'Springer LNCS requires llncs.cls.',
  },
  {
    id: 'nature',
    name: 'Nature Journal',
    documentClass: 'article',
    documentOptions: ['11pt'],
    packages: [
      { name: 'amsmath' },
      { name: 'graphicx' },
      { name: 'natbib', options: ['numbers', 'compress'] },
      { name: 'geometry', options: ['margin=2cm'] },
      { name: 'hyperref' },
      { name: 'booktabs' },
    ],
    bibliographyStyle: 'naturemag',
    bibliographyEngine: 'bibtex',
    notes: 'Nature uses superscript numbered references.',
  },
  {
    id: 'plos',
    name: 'PLOS ONE',
    documentClass: 'article',
    documentOptions: ['10pt'],
    packages: [
      { name: 'amsmath' },
      { name: 'graphicx' },
      { name: 'natbib', options: ['numbers'] },
      { name: 'geometry', options: ['margin=2.54cm'] },
      { name: 'hyperref' },
      { name: 'booktabs' },
      { name: 'setspace' },
      { name: 'lineno' },
    ],
    preambleExtras: [
      '\\doublespacing',
      '\\linenumbers',
    ],
    bibliographyStyle: 'plos2015',
    bibliographyEngine: 'bibtex',
  },
  {
    id: 'mdpi',
    name: 'MDPI Journals',
    documentClass: 'article',
    documentOptions: ['10pt'],
    packages: [
      { name: 'amsmath' },
      { name: 'amssymb' },
      { name: 'graphicx' },
      { name: 'booktabs' },
      { name: 'hyperref' },
      { name: 'natbib', options: ['numbers', 'super'] },
      { name: 'geometry', options: ['a4paper', 'margin=2cm'] },
    ],
    bibliographyStyle: 'mdpi',
    bibliographyEngine: 'bibtex',
  },
  {
    id: 'acs',
    name: 'ACS Publications',
    documentClass: 'achemso',
    documentOptions: ['journal=jacs', 'manuscript=article'],
    packages: [
      { name: 'amsmath' },
      { name: 'graphicx' },
      { name: 'booktabs' },
      { name: 'chemformula' },
    ],
    bibliographyStyle: 'achemso',
    bibliographyEngine: 'bibtex',
    notes: 'Requires achemso.cls. Set journal= option appropriately.',
  },
  {
    id: 'wiley',
    name: 'Wiley-Blackwell',
    documentClass: 'article',
    documentOptions: ['12pt'],
    packages: [
      { name: 'amsmath' },
      { name: 'graphicx' },
      { name: 'natbib', options: ['authoryear', 'round'] },
      { name: 'geometry', options: ['margin=2.5cm'] },
      { name: 'booktabs' },
      { name: 'hyperref' },
      { name: 'setspace' },
    ],
    preambleExtras: ['\\doublespacing'],
    bibliographyStyle: 'wiley-apa',
    bibliographyEngine: 'bibtex',
  },
  {
    id: 'wiley-reviews',
    name: 'Wiley Interdisciplinary Reviews',
    documentClass: 'article',
    documentOptions: ['12pt'],
    packages: [
      { name: 'amsmath' },
      { name: 'graphicx' },
      { name: 'natbib', options: ['authoryear'] },
      { name: 'geometry', options: ['margin=2.5cm'] },
      { name: 'booktabs' },
      { name: 'hyperref' },
    ],
    bibliographyStyle: 'wiley-apa',
    bibliographyEngine: 'bibtex',
  },
  {
    id: 'taylor',
    name: 'Taylor & Francis',
    documentClass: 'tfp',
    documentOptions: [],
    packages: [
      { name: 'amsmath' },
      { name: 'graphicx' },
      { name: 'natbib' },
      { name: 'booktabs' },
      { name: 'hyperref' },
    ],
    bibliographyStyle: 'tfnlm',
    bibliographyEngine: 'bibtex',
    notes: 'Use T&F class files from journal website.',
  },
  {
    id: 'frontiers',
    name: 'Frontiers Journals',
    documentClass: 'frontiersinHLTH',
    documentOptions: [],
    packages: [
      { name: 'amsmath' },
      { name: 'graphicx' },
      { name: 'booktabs' },
      { name: 'url' },
      { name: 'hyperref' },
    ],
    bibliographyStyle: 'frontiersinHLTH',
    bibliographyEngine: 'bibtex',
    notes: 'Frontiers provides per-discipline cls files.',
  },
  {
    id: 'iop',
    name: 'IOP Publishing (Journal of Physics)',
    documentClass: 'iopart',
    documentOptions: [],
    packages: [
      { name: 'amsmath' },
      { name: 'amssymb' },
      { name: 'graphicx' },
      { name: 'booktabs' },
      { name: 'iopams' },
    ],
    bibliographyStyle: 'iopart-num',
    bibliographyEngine: 'bibtex',
    notes: 'Requires iopart.cls from IOP.',
  },
  {
    id: 'sage',
    name: 'SAGE Publications',
    documentClass: 'sagej',
    documentOptions: [],
    packages: [
      { name: 'amsmath' },
      { name: 'graphicx' },
      { name: 'natbib' },
      { name: 'booktabs' },
      { name: 'hyperref' },
    ],
    bibliographyStyle: 'sageh',
    bibliographyEngine: 'bibtex',
    notes: 'Requires sagej.cls from SAGE.',
  },
  {
    id: 'cambridge',
    name: 'Cambridge University Press',
    documentClass: 'article',
    documentOptions: ['12pt'],
    packages: [
      { name: 'amsmath' },
      { name: 'graphicx' },
      { name: 'natbib', options: ['authoryear', 'round'] },
      { name: 'geometry', options: ['margin=2.5cm'] },
      { name: 'booktabs' },
      { name: 'hyperref' },
    ],
    bibliographyStyle: 'agsm',
    bibliographyEngine: 'bibtex',
  },
  {
    id: 'oxford',
    name: 'Oxford University Press',
    documentClass: 'oup-authoring-template',
    documentOptions: ['DOUBLE'],
    packages: [
      { name: 'amsmath' },
      { name: 'graphicx' },
      { name: 'natbib' },
      { name: 'booktabs' },
      { name: 'hyperref' },
    ],
    bibliographyStyle: 'plain',
    bibliographyEngine: 'bibtex',
    notes: 'Use OUP authoring template. Available from OUP.',
  },
  {
    id: 'rsc',
    name: 'RSC Journals',
    documentClass: 'rsc',
    documentOptions: ['article', '9pt'],
    packages: [
      { name: 'amsmath' },
      { name: 'graphicx' },
      { name: 'chemformula' },
      { name: 'booktabs' },
    ],
    bibliographyStyle: 'rsc',
    bibliographyEngine: 'bibtex',
    notes: 'Requires rsc.cls from the Royal Society of Chemistry.',
  },
  {
    id: 'hindawi',
    name: 'Hindawi (Open Access)',
    documentClass: 'article',
    documentOptions: ['10pt'],
    packages: [
      { name: 'amsmath' },
      { name: 'graphicx' },
      { name: 'natbib', options: ['numbers'] },
      { name: 'geometry', options: ['margin=2cm'] },
      { name: 'booktabs' },
      { name: 'hyperref' },
    ],
    bibliographyStyle: 'vancouver',
    bibliographyEngine: 'bibtex',
  },
  {
    id: 'spie',
    name: 'SPIE (Optical Engineering)',
    documentClass: 'spie',
    documentOptions: [],
    packages: [
      { name: 'amsmath' },
      { name: 'graphicx' },
      { name: 'booktabs' },
    ],
    bibliographyStyle: 'spiebib',
    bibliographyEngine: 'bibtex',
    notes: 'Requires spie.cls from SPIE.',
  },
  {
    id: 'intechopen',
    name: 'IntechOpen Book Chapter',
    documentClass: 'article',
    documentOptions: ['12pt'],
    packages: [
      { name: 'amsmath' },
      { name: 'graphicx' },
      { name: 'natbib', options: ['authoryear'] },
      { name: 'geometry', options: ['margin=2.5cm'] },
      { name: 'booktabs' },
      { name: 'hyperref' },
    ],
    bibliographyStyle: 'apa',
    bibliographyEngine: 'biber',
  },
  {
    id: 'asme',
    name: 'ASME Journal',
    documentClass: 'asmejour',
    documentOptions: [],
    packages: [
      { name: 'amsmath' },
      { name: 'graphicx' },
      { name: 'booktabs' },
      { name: 'siunitx' },
    ],
    bibliographyStyle: 'asme2e',
    bibliographyEngine: 'bibtex',
    notes: 'Requires asmejour.cls from ASME.',
  },
  {
    id: 'asce',
    name: 'ASCE Journal (Civil Engineering)',
    documentClass: 'newlfm',
    documentOptions: ['12pt'],
    packages: [
      { name: 'amsmath' },
      { name: 'graphicx' },
      { name: 'natbib', options: ['authoryear'] },
      { name: 'booktabs' },
      { name: 'hyperref' },
    ],
    bibliographyStyle: 'ascelike',
    bibliographyEngine: 'bibtex',
  },
  {
    id: 'aaas',
    name: 'Science (AAAS)',
    documentClass: 'article',
    documentOptions: ['11pt'],
    packages: [
      { name: 'amsmath' },
      { name: 'graphicx' },
      { name: 'natbib', options: ['numbers', 'super'] },
      { name: 'geometry', options: ['margin=2cm'] },
      { name: 'booktabs' },
      { name: 'hyperref' },
    ],
    bibliographyStyle: 'Science',
    bibliographyEngine: 'bibtex',
    notes: 'Science uses superscript numbered citations.',
  },
  {
    id: 'cell-press',
    name: 'Cell Press',
    documentClass: 'article',
    documentOptions: ['11pt'],
    packages: [
      { name: 'amsmath' },
      { name: 'graphicx' },
      { name: 'natbib', options: ['numbers', 'sort&compress'] },
      { name: 'geometry', options: ['margin=2cm'] },
      { name: 'booktabs' },
      { name: 'hyperref' },
    ],
    bibliographyStyle: 'cell',
    bibliographyEngine: 'bibtex',
  },
  {
    id: 'annual-reviews',
    name: 'Annual Reviews',
    documentClass: 'ar-article',
    documentOptions: [],
    packages: [
      { name: 'amsmath' },
      { name: 'graphicx' },
      { name: 'natbib', options: ['authoryear'] },
      { name: 'booktabs' },
      { name: 'hyperref' },
    ],
    bibliographyStyle: 'ar-style3',
    bibliographyEngine: 'bibtex',
    notes: 'Annual Reviews requires ar-article.cls.',
  },
  {
    id: 'de-gruyter',
    name: 'De Gruyter',
    documentClass: 'dgjournal',
    documentOptions: [],
    packages: [
      { name: 'amsmath' },
      { name: 'graphicx' },
      { name: 'natbib', options: ['authoryear'] },
      { name: 'booktabs' },
      { name: 'hyperref' },
    ],
    bibliographyStyle: 'chicago',
    bibliographyEngine: 'bibtex',
  },
  {
    id: 'emerald',
    name: 'Emerald Publishing',
    documentClass: 'emerald',
    documentOptions: [],
    packages: [
      { name: 'amsmath' },
      { name: 'graphicx' },
      { name: 'natbib', options: ['authoryear'] },
      { name: 'booktabs' },
      { name: 'hyperref' },
    ],
    bibliographyStyle: 'emerald-harv',
    bibliographyEngine: 'bibtex',
  },
  {
    id: 'copernicus',
    name: 'Copernicus (EGU Journals)',
    documentClass: 'copernicus',
    documentOptions: [],
    packages: [
      { name: 'amsmath' },
      { name: 'graphicx' },
      { name: 'natbib', options: ['authoryear', 'round'] },
      { name: 'booktabs' },
      { name: 'hyperref' },
    ],
    bibliographyStyle: 'copernicus',
    bibliographyEngine: 'bibtex',
    notes: 'Requires copernicus.cls from EGU.',
  },
  {
    id: 'pip',
    name: 'Progress in Photovoltaics',
    documentClass: 'article',
    documentOptions: ['12pt'],
    packages: [
      { name: 'amsmath' },
      { name: 'graphicx' },
      { name: 'natbib', options: ['authoryear', 'round'] },
      { name: 'geometry', options: ['margin=2.5cm'] },
      { name: 'booktabs' },
      { name: 'siunitx' },
      { name: 'hyperref' },
    ],
    bibliographyStyle: 'wiley-apa',
    bibliographyEngine: 'bibtex',
  },
  {
    id: 'solar-energy',
    name: 'Solar Energy',
    documentClass: 'elsarticle',
    documentOptions: ['review', '12pt'],
    packages: [
      { name: 'amsmath' },
      { name: 'graphicx' },
      { name: 'natbib', options: ['numbers'] },
      { name: 'booktabs' },
      { name: 'siunitx' },
      { name: 'hyperref' },
    ],
    bibliographyStyle: 'elsarticle-num',
    bibliographyEngine: 'bibtex',
  },
  {
    id: 'solar-energy-mse',
    name: 'Solar Energy Materials & Solar Cells',
    documentClass: 'elsarticle',
    documentOptions: ['review', '12pt'],
    packages: [
      { name: 'amsmath' },
      { name: 'graphicx' },
      { name: 'natbib', options: ['numbers'] },
      { name: 'booktabs' },
      { name: 'siunitx' },
      { name: 'chemformula' },
      { name: 'hyperref' },
    ],
    bibliographyStyle: 'elsarticle-num',
    bibliographyEngine: 'bibtex',
  },
  {
    id: 'jpv',
    name: 'IEEE Journal of Photovoltaics',
    documentClass: 'IEEEtran',
    documentOptions: ['journal', 'twocolumn', '10pt'],
    packages: [
      { name: 'cite' },
      { name: 'amsmath' },
      { name: 'graphicx' },
      { name: 'siunitx' },
      { name: 'booktabs' },
      { name: 'hyperref', options: ['colorlinks=false'] },
    ],
    bibliographyStyle: 'IEEEtran',
    bibliographyEngine: 'bibtex',
  },
  {
    id: 'jap',
    name: 'Journal of Applied Physics',
    documentClass: 'article',
    documentOptions: ['12pt'],
    packages: [
      { name: 'amsmath' },
      { name: 'amssymb' },
      { name: 'graphicx' },
      { name: 'natbib', options: ['numbers', 'sort&compress'] },
      { name: 'geometry', options: ['margin=2.5cm'] },
      { name: 'siunitx' },
      { name: 'booktabs' },
      { name: 'hyperref' },
    ],
    bibliographyStyle: 'apsrev4-2',
    bibliographyEngine: 'bibtex',
  },
  {
    id: 'apl',
    name: 'Applied Physics Letters',
    documentClass: 'article',
    documentOptions: ['11pt'],
    packages: [
      { name: 'amsmath' },
      { name: 'graphicx' },
      { name: 'natbib', options: ['numbers'] },
      { name: 'geometry', options: ['margin=2cm'] },
      { name: 'siunitx' },
      { name: 'booktabs' },
      { name: 'hyperref' },
    ],
    bibliographyStyle: 'apsrev4-2',
    bibliographyEngine: 'bibtex',
  },
  {
    id: 'sciencedirect-review',
    name: 'ScienceDirect Review Article',
    documentClass: 'elsarticle',
    documentOptions: ['review', '12pt', 'authoryear'],
    packages: [
      { name: 'amsmath' },
      { name: 'graphicx' },
      { name: 'natbib', options: ['numbers'] },
      { name: 'booktabs' },
      { name: 'lineno' },
      { name: 'hyperref' },
    ],
    bibliographyStyle: 'elsarticle-num',
    bibliographyEngine: 'bibtex',
  },
  {
    id: 'thesis',
    name: 'Thesis / Dissertation',
    documentClass: 'book',
    documentOptions: ['12pt', 'oneside'],
    packages: [
      { name: 'amsmath' },
      { name: 'amssymb' },
      { name: 'graphicx' },
      { name: 'natbib', options: ['authoryear', 'round'] },
      { name: 'geometry', options: ['margin=2.5cm'] },
      { name: 'booktabs' },
      { name: 'hyperref' },
      { name: 'setspace' },
      { name: 'tocloft' },
      { name: 'fancyhdr' },
    ],
    preambleExtras: [
      '\\doublespacing',
      '\\setcounter{tocdepth}{3}',
    ],
    bibliographyStyle: 'apa',
    bibliographyEngine: 'biber',
  },
  {
    id: 'technical-report',
    name: 'Technical Report',
    documentClass: 'report',
    documentOptions: ['12pt', 'oneside'],
    packages: [
      { name: 'amsmath' },
      { name: 'graphicx' },
      { name: 'natbib', options: ['numbers'] },
      { name: 'geometry', options: ['margin=2.5cm'] },
      { name: 'booktabs' },
      { name: 'hyperref' },
      { name: 'fancyhdr' },
      { name: 'listings' },
    ],
    bibliographyStyle: 'IEEEtran',
    bibliographyEngine: 'bibtex',
  },
  {
    id: 'custom',
    name: 'Custom Template',
    documentClass: 'article',
    documentOptions: ['11pt', 'a4paper'],
    packages: [
      { name: 'amsmath' },
      { name: 'graphicx' },
      { name: 'natbib' },
      { name: 'geometry', options: ['margin=2.5cm'] },
      { name: 'booktabs' },
      { name: 'hyperref' },
    ],
    bibliographyStyle: 'plain',
    bibliographyEngine: 'bibtex',
  },
];

/** Look up a LaTeX template by journal template ID. */
export function getLatexTemplate(id: string): LaTeXTemplate | undefined {
  return latexTemplateRegistry.find((t) => t.id === id);
}

/** Generate the LaTeX preamble string for a given template. */
export function generatePreamble(template: LaTeXTemplate): string {
  const classOpts = template.documentOptions.length
    ? `[${template.documentOptions.join(',')}]`
    : '';

  const packageLines = template.packages
    .map((pkg) => {
      const opts = pkg.options ? `[${pkg.options.join(',')}]` : '';
      return `\\usepackage${opts}{${pkg.name}}`;
    })
    .join('\n');

  const extras = (template.preambleExtras ?? []).join('\n');

  return [
    `\\documentclass${classOpts}{${template.documentClass}}`,
    packageLines,
    extras,
  ]
    .filter(Boolean)
    .join('\n');
}
