import { NextRequest, NextResponse } from 'next/server';

interface ShareRequest {
  meetingId: string;
  action: 'email' | 'link' | 'slack';
  recipients?: string[];
  channelId?: string;
  meetingTitle?: string;
  summary?: string;
  actionItems?: string[];
  permissions?: 'view' | 'comment' | 'edit';
}

function generateEmailHtml(title: string, summary: string, actionItems: string[]): string {
  return `
    <!DOCTYPE html>
    <html>
    <head><style>
      body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; color: #333; max-width: 600px; margin: 0 auto; }
      .header { background: linear-gradient(135deg, #6366f1, #8b5cf6); color: white; padding: 24px; border-radius: 8px 8px 0 0; }
      .content { padding: 24px; background: #f8fafc; }
      .action-item { padding: 8px 12px; margin: 4px 0; background: white; border-left: 3px solid #6366f1; border-radius: 4px; }
      .footer { padding: 16px 24px; background: #f1f5f9; border-radius: 0 0 8px 8px; font-size: 12px; color: #64748b; }
    </style></head>
    <body>
      <div class="header">
        <h2 style="margin:0">Meeting Summary: ${title}</h2>
        <p style="margin:8px 0 0; opacity:0.9">Auto-generated by Vidyalaya Office</p>
      </div>
      <div class="content">
        <h3>Summary</h3>
        <p>${summary}</p>
        ${actionItems.length > 0 ? `
          <h3>Action Items</h3>
          ${actionItems.map((item) => `<div class="action-item">☐ ${item}</div>`).join('')}
        ` : ''}
      </div>
      <div class="footer">
        <p>Sent via Vidyalaya Office · <a href="https://vidyalaya.dev">Open in Vidyalaya</a></p>
      </div>
    </body>
    </html>
  `;
}

function generateSlackPayload(title: string, summary: string, actionItems: string[]) {
  return {
    blocks: [
      {
        type: 'header',
        text: { type: 'plain_text', text: `📋 Meeting Notes: ${title}` },
      },
      { type: 'divider' },
      {
        type: 'section',
        text: { type: 'mrkdwn', text: `*Summary*\n${summary}` },
      },
      ...(actionItems.length > 0
        ? [
            { type: 'divider' },
            {
              type: 'section',
              text: {
                type: 'mrkdwn',
                text: `*Action Items*\n${actionItems.map((item) => `• ${item}`).join('\n')}`,
              },
            },
          ]
        : []),
      { type: 'divider' },
      {
        type: 'context',
        elements: [{ type: 'mrkdwn', text: '_Shared from Vidyalaya Office_' }],
      },
    ],
  };
}

export async function POST(request: NextRequest) {
  try {
    const data: ShareRequest = await request.json();

    if (!data.meetingId || !data.action) {
      return NextResponse.json({ error: 'meetingId and action are required' }, { status: 400 });
    }

    const title = data.meetingTitle || 'Meeting Notes';
    const summary = data.summary || '';
    const actionItems = data.actionItems || [];

    switch (data.action) {
      case 'email': {
        if (!data.recipients || data.recipients.length === 0) {
          return NextResponse.json({ error: 'Recipients are required for email sharing' }, { status: 400 });
        }
        const emailHtml = generateEmailHtml(title, summary, actionItems);
        // In production, this would integrate with an email service (SendGrid, SES, etc.)
        return NextResponse.json({
          success: true,
          action: 'email',
          recipients: data.recipients,
          emailHtml,
          message: `Meeting summary sent to ${data.recipients.length} recipient(s)`,
        });
      }

      case 'link': {
        const token = Math.random().toString(36).slice(2) + Date.now().toString(36);
        const shareUrl = `https://vidyalaya.dev/meetings/shared/${data.meetingId}?token=${token}`;
        return NextResponse.json({
          success: true,
          action: 'link',
          shareUrl,
          permissions: data.permissions || 'view',
          expiresAt: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(),
        });
      }

      case 'slack': {
        if (!data.channelId) {
          return NextResponse.json({ error: 'channelId is required for Slack sharing' }, { status: 400 });
        }
        const slackPayload = generateSlackPayload(title, summary, actionItems);
        // In production, this would post to Slack via their API
        return NextResponse.json({
          success: true,
          action: 'slack',
          channelId: data.channelId,
          payload: slackPayload,
          message: 'Meeting summary posted to Slack channel',
        });
      }

      default:
        return NextResponse.json({ error: `Unsupported action: ${data.action}` }, { status: 400 });
    }
  } catch (error) {
    const message = error instanceof Error ? error.message : 'Share failed';
    return NextResponse.json({ error: message }, { status: 500 });
  }
}
